dashboard/charts/routes.py
from flask import Blueprint , render_template, request, flash, redirect, url_for
from dashboard.models import Postdevice
from dashboard.plots.routes import validList
from cloudant.client import Cloudant
from cloudant.result import Result
import time
import pandas as pd
import numpy as np
import json

# define the blueprint
charts = Blueprint('charts',__name__)


# # select the name of the database
#  DEVICESIN IN DIFFERENT DATABASES THAT WE CAN READ FROM
ANNE=['Anne - Ceiling lamp above dining table','Anne - Bedroom light','Anne - Main ceiling light','Anne - Crownstone Plug 22','Anne - Crownstone Plug 24','Anne - Crownstone Plug 28','Anne - Crownstone Plug 29','Anne - Crownstone Corner','Anne - Standing lamp','Anne - Guidestone Kitchen','Anne - Dishwasher']
PEET=['Audio Amplifier','Battery Charger','Charger','Coffee Maker (Senseo)','Digital TV Receiver','Freezer','Subwoofer','Tumble Dryer','USB-Hub','WiFi Router','Desktop Computer','Chandelier Dining Room','Vase Lamp']
DEFAULT=['Alarm Clock Radio','Bean-To-Cup Coffee Maker','Computer Printer','Dishwasher','Electrical Oven','Fridge & Freezer','Hair Dryer','Hair Straightener','Handmixer','Humidifier - Zahra','Immersion Blender','Iron','Juicer','Laptop Computer (Carolyns)','LCD Monitor (Carolyns)','Microwave','Nintendo Switch','Playstation 4','Toaster','Vacuum Cleaner','Washing Machine','Water Kettle','iMac','Philips Hue','Almende Humidifier','MacBook Pro (Meris)','Magimix (Andries)','LCD Monitor-Almende','dashboardpi3','Robert','Sandwich Maker','Induction Cooker','Egg Cooker','Big Brother','Beamer']


@charts.route("/chart")
def chart():
    alldevices=Postdevice.query.all()
    return render_template('charts.html',title='Monitor Power Usage', legend='Select a Device', alldevices=alldevices)


def getdatabase(db_name, start_time, req_time):
    user = "######"
    password = "######"
    url="################################"
    link=(url % (user, password))
    ddoc_id = 'powerUsage'
    view_id = 'byPiTimeAndID'

    client=Cloudant(user, password, url=url, connect=True)
    db    = client.get(db_name, remote=True)
    view  = db.get_design_document(ddoc_id).get_view(view_id)
    views = view( startkey=[str(req_time)], endkey=[str(start_time),{}], stale= 'update_after', stable = True, update ='lazy')['rows']
    keys  = [result.get('key') for result in views]
    values= [result.get('value') for result in views]

    if len(keys) ==0 :
        # flash ('No Data in this time', 'success')
        df=[]
        pattern = '%d.%m.%Y %H:%M:%S'
        start=time.strftime(pattern, time.localtime(start_time))
        end=time.strftime(pattern, time.localtime(req_time))
        print("No data is availble for this time between ", start, "and", end)
        # raise TypeError ("No data is availble for this time between ", start, "and", end)
    else:
        #flash ('Data exists for this time', 'success')
        dfkeys=pd.DataFrame(keys,columns=['localtimestamp', 'crownid', 'macAddress'])
        dfvalues=pd.DataFrame(values,columns=['powerUsage','LSB Timestamp'])
        df_all=pd.concat([dfkeys,dfvalues],axis=1)
        df_all['Datetime']=pd.to_datetime(df_all['localtimestamp'], unit='s', utc=True)
        df_all.set_index('Datetime', inplace=True)
        df_all.index = df_all.index.tz_convert('Europe/Amsterdam')
        Devicelist=validList()
        df = df_all.loc[np.isin(df_all['macAddress'].tolist() ,Devicelist["device_macaddress"])]
        return (df)


# get new data every time it is called by the vis chart in the charts.html file
@charts.route('/_update')
def update():
    # crownID, deviceName, macaddress are variables send by vis chart
    crownID=str(request.args.get('crownID', 0, type=int))
    deviceName=str(request.args.get('deviceName'));
    macaddress=str(request.args.get('macaddress'));
    macaddress=macaddress.lower()
    print('crown id is:' ,crownID,' for :', deviceName)
    timenow=int(time.time()) #curent moment

    # check which database the device is in
    if deviceName in DEFAULT:
        db_name = 'default'
    elif deviceName in PEET:
        db_name = 'peet'
    elif deviceName in ANNE:
        db_name = 'anne'

    df=getdatabase(db_name,timenow,timenow-10) # read database from 10 seconds ago till now
    if not isinstance(df, pd.DataFrame):
        print("no View created for this query")
        values_y='NaN'
        value_y= json.dumps(values_y)
        return value_y
    else :
        df_filtered= df.loc[(df['crownid'] == crownID) & (df['macAddress'] == macaddress) ].sort_values( "localtimestamp")
        df_filtered.drop_duplicates(inplace=True)
        values_y= pd.to_numeric(df_filtered['powerUsage']).tolist()
        # divide by eight
        values_y[:] = [x / 8 for x in values_y]
        values_x= json.dumps(pd.to_numeric(df_filtered['localtimestamp']).tolist())
        if values_y ==[]:
            print("no data availble")
            values_y='NaN'
            value_y= json.dumps(values_y)
            return value_y
        else:
            value_y=json.dumps(values_y[-1]) #get the last data to get the current time
            print("time is :   " , values_x)
            print("Power Usage IS:   ",value_y)
            return value_y

dashboard/device/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request
from dashboard import db
from dashboard.device.forms import  DeviceForm
from dashboard.models import Postdevice  # we have to import this after db to remove errors for importing db and reading from db which dose not exist yet

device = Blueprint('device',__name__)


@device.route('/device/new',methods=['GET','POST'])
def new_device():
    form = DeviceForm()
    if form.validate_on_submit():
        pp= Postdevice(name= form.name.data, crownID = form.crownID.data , macAddress= form.macAddress.data )
        db.session.add(pp)
        db.session.commit()
        flash ('Your device has ben added', 'success')
        return redirect(url_for('main.home'))
    return render_template ('create_device.html', title='New Device', form=form, legend='New Device')


@device.route('/device/<int:post_id>')
def detials(post_id):
    detials=Postdevice.query.get_or_404(post_id)
    return render_template('details.html', title= detials.name, post=detials)


@device.route('/device/<int:post_id>/update', methods=['GET','POST'])
def detials_update(post_id):
    update=Postdevice.query.get_or_404(post_id)
    form = DeviceForm()
    if form.validate_on_submit():
         update.name = form.name.data
         update.crownID= form.crownID.data
         update.macAddress = form.macAddress.data
         db.session.commit()
         flash("Your device is updated", "success")
         return redirect(url_for('device.detials',post_id=update.id))
    elif request.method == 'GET':
        form.name.data = update.name
        form.crownID.data = update.crownID
        form.macAddress.data = update.macAddress
    return render_template ('create_device.html', title='Update Device', form=form, legend='Update Device')


@device.route('/device/<int:post_id>/delete', methods=['POST'])
def delete_device (post_id):
    device=Postdevice.query.get_or_404(post_id)
    db.session.delete(device)
    db.session.commit()
    flash("The device has been deleted", "success")
    return redirect(url_for("main.home"))

dashboard/main/routes.py
from flask import Blueprint, render_template, request
from dashboard.models import Postdevice
from dashboard.plots.routes import validList

main = Blueprint('main',__name__)


@main.route('/home') # these both will go to home
def home():
    page= request.args.get('page', 1, type = int)
    posts = Postdevice.query.order_by(Postdevice.crownID.asc()).paginate(per_page = 10, page=page) # get all devices added as posts and order by crownID and post the detials of each 10 devices in one page
    postnumber=len(Postdevice.query.all())
    return render_template('home.html',posts=posts, postnumber=postnumber)

@main.route('/')
@main.route('/about')
def about():
    Devicelist=validList()  # valid mac adresses ( adresses form the posted devices)
    length=len(Devicelist["device_list_posted"])
    return render_template('about.html',Devicelist=Devicelist, length=length)

dashboard/plots/routes.py
from flask import Blueprint , render_template, request, flash, redirect, url_for
from dashboard import db
from dashboard.models import Postdevice
from matplotlib.figure import Figure
from cloudant.client import Cloudant
from cloudant.result import Result
import time
from datetime import datetime
import pandas as pd
import numpy as np
import json
# for view plot page
import plotly
import plotly.graph_objs as go


plots = Blueprint('plots',__name__)


user = "########"
password = "##############"
url="##################################"
link=(url % (user, password))
db_name = 'default' #'anne' #''default' #'peet' #'test'peet' #'test'default' #
ddoc_id = 'powerUsage'
view_id = 'byPiTimeAndID'
client=Cloudant(user, password, url=url, connect=True)
db = client.get(db_name, remote=True)
view = db.get_design_document(ddoc_id).get_view(view_id)


class datastore():
    device_names=[]
    device_ids=[]
    db_crownid=[]
    device_macaddress=[]
    db_macaddress=[]
    db_df=[]
    db_time =[]
    db_df=[]
    all_posts=[]
    time_view=[]
globaldata= datastore()


def get_data(start_time,selected_time):
    import time
    req_time =selected_time
    views=view( startkey=[str(req_time)], endkey=[str(start_time),{}], stale= 'update_after', stable = True, update ='lazy')['rows']
    keys=[result.get('key') for result in views]
    values=[result.get('value') for result in views]

    if len(keys) ==0 :
        flash ('No Data in this time', 'success')
        df=[]
        pattern = '%d.%m.%Y %H:%M:%S'
        start=time.strftime(pattern, time.localtime(start_time))
        end=time.strftime(pattern, time.localtime(req_time))
        raise TypeError ("No data is availble for this time between ", start, "and", end)
    else:
        dfkeys=pd.DataFrame(keys,columns=['localtimestamp', 'crownid', 'macAddress'])
        dfvalues=pd.DataFrame(values,columns=['powerUsage','LSB Timestamp'])
        df_all=pd.concat([dfkeys,dfvalues],axis=1)
        df_all['Datetime']=pd.to_datetime(df_all['localtimestamp'], unit='s', utc=True)
        df_all.set_index('Datetime', inplace=True)
        df_all.index = df_all.index.tz_convert('Europe/Amsterdam')
        validList()
        df = df_all.loc[np.isin(df_all['macAddress'].tolist() ,[globaldata.device_macaddress])]
        return (df)

@plots.route('/viewplot')
def viewplot():
    feature="Line"
    global globaldata
    post=Postdevice.query.all()
    globaldata.all_posts=post
    epoch_timenow = int(time.time())
    globaldata.time_view=epoch_timenow
    tt=epoch_timenow -600 # (10 minits)
    df=get_data(epoch_timenow,tt)
    print(df)
    globaldata.db_df=df
    pt=createPlot(feature,df)
    validList()
    print('plotly from ' ,epoch_timenow, " till  " , tt)
    return render_template('plots.html',plot=pt,feature= "Line" , posts=post , title='Plot last few seconds' )

def createPlot(feature,df):
        if feature =='Bar' :
            data=[go.Bar(x=df.index, y= pd.to_numeric(df['powerUsage']).tolist())]
            layout = go.Layout(showlegend=True, hovermode='closest')
            fig = go.Figure(data=data, layout=layout)
        elif feature =='Scatter'  :
            data=[go.Scatter(x=df.index, y= pd.to_numeric(df['powerUsage']).tolist(), mode = 'markers')]
            layout = go.Layout(showlegend=True, hovermode='closest')
            fig = go.Figure(data=data, layout=layout)
        else :
            data=[go.Scatter(x=df.index, y= pd.to_numeric(df['powerUsage']).tolist(), mode = 'markers+lines')]
            x =df.index
            y1 = pd.to_numeric(df['powerUsage']).tolist()
            y=[i/8 for i in y1]
            line_plt=go.Scatter(x=x, y=y, mode = 'markers+lines',marker=dict(color='blue'),name='linear-data')
            # moving median ( pd.rolling.meadian is good for timeseries data but if do can be done by np.convolve) check:  https://stackoverflow.com/questions/13728392/moving-average-or-running-mean

            df1 = df[['localtimestamp','powerUsage']]
            df1_median = df1.rolling(window=40, min_periods=2, center=True).median()
            y2=pd.to_numeric(df1_median['powerUsage']).tolist()
            y2=[i/8 for i in y2]
            median_plt=go.Scatter(x=x, y=y2,mode='markers+lines', line=dict(color='red', width=3),name='moving_median')

            # moving mean
            df1_mean = df1.rolling(window=40, min_periods=2, center=True).mean()
            y3=pd.to_numeric(df1_mean['powerUsage']).tolist()
            y3=[i/8 for i in y3]
            mean_plt=go.Scatter(x=x, y=y3,mode='markers+lines', line=dict(color='green', width=3),name='moving_mean')

            layout = go.Layout(
                showlegend=True,
                hovermode='closest',
                title=go.layout.Title(
                    text='Power usage in the last 10 minutes',
                    xref='paper',
                    x=0
                ),
                xaxis=go.layout.XAxis(
                    type= 'date',
                    title=go.layout.xaxis.Title(
                        text='Time is in GMT. Add 2 hours for local time',
                        font=dict(
                            size=18,
                            color='#7f7f7f')
                    )
                ),
                yaxis=go.layout.YAxis(
                    title=go.layout.yaxis.Title(
                        text='Watt',
                        font=dict(
                            size=18,
                            color='#7f7f7f')
                    )
                )
            )
            fig = go.Figure(data=[line_plt,median_plt, mean_plt], layout=layout)

        graphJSON = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)
        return (graphJSON)


@plots.route('/validList')
def validList():
    device_list_posted = Postdevice.query.all()
    device_names = [p.name for p in device_list_posted]
    device_crownids = [p.crownID for p in device_list_posted]
    device_macaddress =  [a.lower() for a in[p.macAddress for p in device_list_posted]]
    globaldata.device_names = device_names
    globaldata.device_ids = device_crownids
    globaldata.device_macaddress =device_macaddress
    return {"device_list_posted" : device_list_posted,
            "device_macaddress":device_macaddress,
            "device_names": device_names,  "device_crownids":device_crownids}

@plots.route('/viewplot/<int:post_id>')
def device_plot(post_id):
    detials=Postdevice.query.get_or_404(post_id)
    print(detials)
    nn=detials.name
    crnid=detials.crownID
    mac=detials.macAddress

    df_all=globaldata.db_df
    if len(df_all) <1 :
        flash ('the data is updating', 'success')
        return redirect(url_for('plots.viewplot'))
    else:
        df_device = df_all.loc[(df_all['crownid']== crnid)  & np.isin(df_all['macAddress'].tolist() ,[globaldata.device_macaddress])]
        pt=createPlot(feature,df_device)
        return render_template('plot_device.html', title= detials.name, name=nn,crownid=crnid, plot=pt,posts=globaldata.all_posts)

dashboard/users/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect
from dashboard import db, bcrypt
from dashboard.users.forms import RegistrationForm, LoginForm
from dashboard.models import User,Postdevice  # we move this below db to remove errors for db
from flask_login import login_user, current_user, logout_user


users = Blueprint('users',__name__)

@users.route('/register',methods=['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect (url_for('main.home'))
    form= RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf_8')
        user =  User(username = form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! you can be able to login','success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)



@users.route('/login',methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect (url_for('main.home'))
    form= LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):  # if the user exists and the password that is entered is valid with what is saved in the databse log the user in
            login_user(user, remember = form.remember.data)
            return redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful, Please check email and password','danger')
    return render_template('login.html', title='login', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

dashboard/templates/about.html
{% extends 'layout.html' %}  
{% block AddToHeader %}

<!-- style to make a table, styles should be always added to the header so should go in header block -->
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 90%;
  padding: 10px;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>

{% endblock AddToHeader %}

{% block content %}

<h1 align =' left'> <strong>PL<font color="blue">AI</font>STER  </strong> </h1>

<article>
    <h3 align =' left'> <strong> About PL<font color="blue">AI</font>STER </strong></h3>
    <p align =' justify'> <b> How and what does use electricity at home?  </b> Energy management is all about monitoring the electricity consumption of the devices in use. Monitoring the power usage per device can help you track the quality of the device.
  <div id="more-1" class="fulltext">
     <p align =' justify'> You can detect how well the device is doing and whether it is consuming the same energy as mentioned on the energy consumption labeling or not. Monitoring energy can even help you to check if the device is degrading and if it is the time to replace it with a new one. Monitoring power consumption of devices is possible by using Crownstones. By extracting the power consumption pattern of different devices we can label which device is being used. With this project, you can track which device is being plugged in and how much power it is using. </p>
 </div>

    <button aria-expanded="false" aria-controls="more-1" class="toggle-content" hidden><span class="text">Read more</span> <span class="visually-hidden"> </span></button>
</article>

<!--  the javascript below is to extend the text if the word Read More is pressed-->

<script type="text/javascript">
  if ('querySelector' in document &&
  	'addEventListener' in window) {

  	var toggleButtons = document.querySelectorAll('.toggle-content');
  	var fullTextWrappers = document.querySelectorAll('.fulltext');
  	var fullText;
  	var toggleButtonText;


  	[].forEach.call(fullTextWrappers, function(fullTextWrapper) {
  		// hide all full text on load
  		fullTextWrapper.setAttribute('hidden', true);
  	});

  	[].forEach.call(toggleButtons, function(toggleButton) {
  		// show toggle more buttons
  		toggleButton.removeAttribute('hidden');

  		// add listener for each button
  		toggleButton.addEventListener('click', function () {

  			fullTextWrapper = this.parentElement.querySelector('.fulltext');
  			toggleButtonText = this.querySelector('.text');

  			// change attributes and text if full text is shown/hidden
  			if (!fullTextWrapper.hasAttribute('hidden')) {
  				toggleButtonText.innerText = 'Read More';
  				fullTextWrapper.setAttribute('hidden', true);
  				toggleButton.setAttribute('aria-expanded', false);
  			} else {
  				toggleButtonText.innerText = 'Show Less';
  				fullTextWrapper.removeAttribute('hidden');
  				toggleButton.setAttribute('aria-expanded', true);
  			}
  		});
  	});
  }
</script>
</br>
<!-- the table below will show all the devices and there crown id and mac address as saved in the SQLite database of Flask . Devicelist is send from Main/routes.py -->
<p > <strong> The table below shows all the devices in this project : </strong> </p>

<table>
  <tr>
    <th>#</th>
    <th>Device</th>
    <th>CrownID</th>
    <th>MAcAddress</th>
  </tr>

    {% for ii  in range(0,length)%}
  <tr>
    <th>{{ii+1}}</th>
    <th>{{Devicelist["device_names"][ii]}}</th>
    <th>{{Devicelist["device_crownids"][ii] }}</th>
    <th>{{Devicelist["device_macaddress"][ii] }}</th>
  </tr>
  {%endfor %}

{% endblock content %}

dashboard/templates/details.html
{% extends 'layout.html' %}
{% block content %}
<h1> Device Details </h1>
<article class="media content-section">
  <img class="rounded-circle article-img" src="{{ url_for('static', filename='pictures/imac.jpg') }}">

  <div class="media-body">
    <div class="article-metadata">  </div>
    <h2 class="article-title" >{{ post.name }}</h2>
    <p><li>      Crown ID : {{ post.crownID }}  </li>
    <li>  Mac Address: {{ post.macAddress }}</li>
    <li> Started at : {{ post.startDate.strftime('%Y-%m-%d') }}</li>
    <li> Stoped at :{{ post.endDate.strftime('%Y-%m-%d') }}</li> </br>

    <div>
      <a class= "btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('device.detials_update', post_id=post.id)}}"> Update </a>
      <button type="button" class= "btn btn-danger btn-sm m-1 mt-1 mb-1" data-toggle="modal" data-target="#deleteModal" name="Delete"> Delete</button>
      </div>
      <!-- Modal -->
       <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
         <div class="modal-dialog" role="document">
           <div class="modal-content">
             <div class="modal-header">
               <h5 class="modal-title" id="deleteModalLabel">Delete Device?</h5>
               <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                 <span aria-hidden="true">&times;</span>
               </button>
             </div>
             <div class="modal-footer">
               <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
               <form action="{{ url_for('device.delete_device', post_id=post.id) }}" method="POST">
                 <input class="btn btn-danger" type="submit" value="Delete">
               </form>
             </div>
           </div>
         </div>
  </div>



</article>
{% endblock content %}

dashboard/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <!--  check the title if  not gived use the default one -->
    {% if title %}
      <title> {{title}}</title>
    {% else %}
      <title> PLAISTER </title>
    {%  endif %}

    <script src="{{ url_for('static', filename='vis/dist/vis.js') }}"></script>
    <link href="{{ url_for('static', filename='vis/dist/vis-timeline-graph2d.min.css') }}" rel="stylesheet" type="text/css" />
    <script src="{{ url_for('static', filename='js/jquery-3.4.0.js') }}"></script>
    <!-- In the block extent below you can add extra Header in each of the pages you would like to  -->
    {% block AddToHeader %}{% endblock %}

</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">PL<font color="blue">AI</font>STER </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
              <a class="nav-item nav-link" href="{{ url_for('plots.viewplot') }}">Plot</a>
              <a class="nav-item nav-link" href="{{ url_for('charts.chart') }}">Charts</a>
            </div>
          </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('device.new_device') }}">Add Device</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
              <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
              <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container-fluid" style="padding: 35px">
      <div class="row">
        <div class="col-lg-12">

          {% block content %}{% endblock %}

        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

dashboard/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml-2">
                <a href="#">Forgot Password?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

dashboard/templates/validlist.html
{% extends 'layout.html' %}
{% block content %}

    <h1>input database</h1>
    <p>device list: </br> {{names}}</p> </br>
    <p>Valid mac address list: </br> {{macs}}</p></br>
    <p>Valid Crown stone ID's : </br>  {{crownids}}</p>
    <p>data saved in couchdb : </br>  {{database}}</p>
<h1>selected device is: <h1>


{% endblock content %}